### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by tomoasleep** [tomoasleep/i18n-tasks-sample-app#1]
for test

**Comment by kakajika** [comment]
LGTM

**Comment by tomoasleep** [comment]
🤖😇🐱  

---

Tomoya Chiba

tomo.asleep@gmail.com

**Comment by tomoasleep** [comment]
Test mail

2016年5月25日(水) 15:31 Tomoya Chiba tomo.asleep@gmail.com:

**Comment by tomoasleep** [comment]
[test](https://github.com/tomoasleep)  

![](https://link.nylas.com/open/6r25hvmf7wcmk4fb884hqxjmn/local-
29e7ea20-a91e?r=cmVwbHkrMDAxNjhhMGEwYjU0NTVhZWEyMjE2ZjIxNTExYzY1YWIzYTk1MGZmZjdjMTMzNTk2OTJjZjAwMDAwMDAxMTM1ZDA0NzQ5MmExNjljZTA5NTY5YTdmQHJlcGx5LmdpdGh1Yi5jb20=)

**Comment by tomoasleep** [comment]
Markdownどのぐらい効くか実験
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del>
  supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

``` javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

![LGTM](http://lgtm.in/p/GdoR4J1mn)
[Qiita](http://qiita.com)

As Kanye West said:

> We're living the future so
> the present is our past.

I think you should use an
`<addr>` element here instead.

# This is an <h1> tag

## This is an <h2> tag

###### This is an <h6> tag

:sparkles: :camel: :boom:

2016年6月23日(木) 18:24 Tomoya Chiba tomo.asleep@gmail.com:

> [test](https://github.com/tomoasleep)
>

**Comment by tomoasleep** [comment]
Hi,

This is a test reply from Inbox.

2016年6月23日(木) 18:34 Tomoya Chiba tomo.asleep@gmail.com:

> Markdownどのぐらい効くか実験
> - [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del>
>   supported
> - [x] list syntax required (any unordered or ordered list supported)
> - [x] this is a complete item
> - [ ] this is an incomplete item
> 
> ``` javascript
> function fancyAlert(arg) {
>   if(arg) {
>     $.facebox({div:'#foo'})
>   }
> }
> ```
> 
> ![LGTM](http://lgtm.in/p/GdoR4J1mn)
> [Qiita](http://qiita.com)
> 
> As Kanye West said:
> 
> > We're living the future so
> > the present is our past.
> 
> I think you should use an
> `<addr>` element here instead.
> 
> # This is an <h1> tag
> 
> ## This is an <h2> tag
> 
> ###### This is an <h6> tag
> 
> :sparkles: :camel: :boom:
> 
> 2016年6月23日(木) 18:24 Tomoya Chiba tomo.asleep@gmail.com:
> 
> [test](https://github.com/tomoasleep)
>

**Comment by tomoasleep** [comment]
Hi,

This is a test reply from Inbox.

2016年5月25日(水) 15:13 Keita Kajiwara notifications@github.com:

**Comment by tomoasleep** [comment]
Hi,
This is test mail from Inbox.
